version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:L8W7owwDh2QsnjlgU6+8U6eoZl6pZB9EZNUdIvF8usM=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: my-app
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: my-app
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

  web:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:


